"""Add relationships between Bank, User, and Account-Re

Revision ID: 1d474c349361
Revises: 7c723172ac47
Create Date: 2024-11-09 18:29:43.423566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d474c349361'
down_revision: Union[str, None] = '7c723172ac47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
