"""Added email and password on customer

Revision ID: 3e3a1ce166b1
Revises: c64e8ffab114
Create Date: 2024-11-18 02:33:09.789723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3a1ce166b1'
down_revision: Union[str, None] = 'c64e8ffab114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('email', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('password', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'customers', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_column('customers', 'password')
    op.drop_column('customers', 'email')
    # ### end Alembic commands ###
