"""Removed account id from the Bank User

Revision ID: 419d8aa2c1f8
Revises: 922314dd9fb1
Create Date: 2024-11-09 18:24:18.941993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '419d8aa2c1f8'
down_revision: Union[str, None] = '922314dd9fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bank_user_account_id_fkey', 'bank_user', type_='foreignkey')
    op.drop_column('bank_user', 'account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_user', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('bank_user_account_id_fkey', 'bank_user', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###
