"""Fix BankUser relationship mappings

Revision ID: 59fa2fb618b0
Revises: 1d474c349361
Create Date: 2024-11-09 18:34:14.726132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59fa2fb618b0'
down_revision: Union[str, None] = '1d474c349361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
