"""Rename password to encrypted_password

Revision ID: 6d5e5ba0ba5e
Revises: 657f5352e4a5
Create Date: 2024-12-01 17:41:15.653409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d5e5ba0ba5e'
down_revision: Union[str, None] = '657f5352e4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('encrypted_password', sa.String(), nullable=True))
    op.drop_column('customers', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('customers', 'encrypted_password')
    # ### end Alembic commands ###
